trigger:
- master
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86|x64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [xml]$xmlDoc = Get-Content $(Build.SourcesDirectory)\Files.Package\Package.appxmanifest
      $xmlDoc.Package.Identity.Name="49306atecsolution.FilesUWP"
      $xmlDoc.Package.Properties.DisplayName="Files UWP - Preview"
      $xmlDoc.Package.Applications.Application.VisualElements.DisplayName="Files UWP - Preview"
      $xmlDoc.Save('$(Build.SourcesDirectory)\Files.Package\Package.appxmanifest')
    failOnStderr: true

- task: DownloadSecureFile@1
  name: signingCert
  displayName: 'Download Files UWP build certificate'
  inputs:
    secureFile: 'Certificate.pfx'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    platform: 'x86'
    solution: '**/*.wapproj'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/t:build;_GenerateAppxPackage /p:UapAppxPackageBuildMode=SideLoadOnly  /p:AppxBundle=Never /p:GenerateAppInstallerFile=True /p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)" /p:AppInstallerUri="https://filesuwp.blob.core.windows.net/filesuwp/a/AppxPackages"'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(build.artifactstagingdirectory)'
    azureSubscription: 'Pay-As-You-Go(8ff51d67-ce42-4319-8dc8-4ebd139f7d9e)'
    Destination: 'AzureBlob'
    storage: 'filesuwp'
    ContainerName: 'filesuwp'